name: ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: yarn
    - uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - run: yarn install
    - run: yarn expo install --check
    - run: yarn tsc
    - run: yarn expo prebuild
    - run: yarn expo export
    - run: yarn doctor
      env:
        EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK: false
    - run: yarn eas build --platform android --local
    - run: yarn f-droid
    - run: yarn eas build --platform android --local
    - run: yarn eas build --platform ios --local
    - if: false && github.event_name == 'pull_request'
      uses: expo/expo-github-action/preview@v8
      with:
        command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
    - if: false && github.event_name == 'push'
      run: |
        if git diff --name-only HEAD | grep -E 'app.json|package.json'; then
          yarn eas build --platform all --non-interactive --no-wait
        else
          yarn eas update --auto --non-interactive
        fi
