name: ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  prebuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: yarn
    - uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - run: yarn install
    - run: yarn doctor
      env:
        EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK: false
    - run: yarn tsc
    - run: yarn expo prebuild
    - run: yarn expo export
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
  build:
    needs: prebuild
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
        - artifact: android
          platform: android
          profile: production
          extension: aab
        - artifact: f-droid
          platform: android
          profile: preview # builds apk instead of aab
          extension: apk
        - artifact: ios
          platform: ios
          profile: production
          extension: ipa
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: yarn
    - uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - run: yarn install
    - if: matrix.extension == 'apk'
      run: yarn f-droid
    - run: >-
        yarn eas build --local --non-interactive
        --output alovoa.${{ matrix.extension }}
        --platform ${{ matrix.platform }}
        --profile ${{ matrix.profile }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.extension }}
        path: alovoa.${{ matrix.extension }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.platform }}
  postbuild:
    needs: build
    if: needs.build.result == 'success'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: yarn
    - uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - uses: actions/download-artifact@v4
      with:
        name: android
    - uses: actions/download-artifact@v4
      with:
        name: ios
    - uses: actions/download-artifact@v4
      with:
        name: aab
    - uses: actions/download-artifact@v4
      with:
        name: apk
    - uses: actions/download-artifact@v4
      with:
        name: ipa
    - run: yarn install
    - if: github.event_name == 'pull_request'
      uses: expo/expo-github-action/preview@v8
      with:
        command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
        qr-target: expo-go
    # - if: github.event_name == 'push' # todo: reduce asset count to utilize deploy
    #   run: yarn eas deploy --non-interactive # Failed to create deployment. Your deployment contains over 134 assets, which exceeds the maximum. On the free tier, your deployments may only upload 100 assets. To lift this restriction, upgrade your account to a paid plan.
    - if: github.event_name == 'push'
      run: |
        if git diff --name-only HEAD | grep -E 'app.json|package.json'; then
          yarn eas build --platform all --non-interactive --no-wait
        else
          yarn eas update --auto --non-interactive
        fi
